#!/bin/bash
echo "🚀 HomeLab Indexer Development Environment"
echo ""
echo "Commands:"
echo "  npm install              - Install dependencies"
echo "  npm run dev              - Start all services"
echo "  npm run build            - Build production"
echo "  npm run db:migrate       - Run database migrations"
echo "  npm run test             - Run tests"
echo "  npm run test:acceptance  - Run acceptance tests"
echo ""
echo "Docker:"
echo "  docker-compose up -d     - Start stack"
echo "  docker-compose down      - Stop stack"
echo ""
echo "API Endpoints:"
echo "  POST   /auth/login"
echo "  GET    /devices"
echo "  GET    /devices/{id}"
echo "  GET    /services"
echo "  GET    /services/{id}"
echo "  POST   /scanner/scan-now"
echo "  GET    /reservations"
echo "  POST   /reservations"
echo "  GET    /alerts"
echo "  PATCH  /alerts/{id}/ack"
echo ""
echo "UI: http://localhost:5173"
echo "API: http://localhost:3001"
